<?php

echo '<section class="home-page-intro">';
echo '<div class="wrap">';
echo '<h1 class="title">UC Santa Cruz Brand Guidelines</h1>';
echo '<p class="intro">Chocolate cheesecake danish apple pie. Halvah topping liquorice tart donut. Liquorice cake sweet roll pie bonbon. Cookie lollipop dragée pie cotton candy tiramisu sesame snaps candy chocolate. Brownie chupa chups liquorice gummi bears tart halvah. Caramels liquorice donut jelly-o jelly. Liquorice liquorice candy canes biscuit.</p>';

echo '</div>';
echo '</section>';
echo '<section>';
echo '<div class="wrap">';
echo '<div class="one-fourth first">';
echo '<p>Ice cream cake candy cotton candy brownie. Chocolate bar pudding croissant pie chocolate cake chocolate candy chocolate bar brownie. Jelly-o bear claw gummi bears. Icing cake pie biscuit danish chocolate bar. Apple pie croissant powder cupcake bear claw jelly cookie marzipan. Chupa chups sweet chocolate cake candy fruitcake. Chocolate cake liquorice chupa chups. Marzipan carrot cake caramels. Jujubes dragée jelly-o cupcake caramels jelly gummies carrot cake tootsie roll. Sugar plum oat cake candy cake donut chocolate cake macaroon. Pudding muffin gingerbread tootsie roll tootsie roll lollipop. Icing halvah jelly beans muffin.</p>';
echo '</div>';
echo '<div class="one-fourth">';
echo '<p>Ice cream cake candy cotton candy brownie. Chocolate bar pudding croissant pie chocolate cake chocolate candy chocolate bar brownie. Jelly-o bear claw gummi bears. Icing cake pie biscuit danish chocolate bar. Apple pie croissant powder cupcake bear claw jelly cookie marzipan. Chupa chups sweet chocolate cake candy fruitcake. Chocolate cake liquorice chupa chups. Marzipan carrot cake caramels. Jujubes dragée jelly-o cupcake caramels jelly gummies carrot cake tootsie roll. Sugar plum oat cake candy cake donut chocolate cake macaroon. Pudding muffin gingerbread tootsie roll tootsie roll lollipop. Icing halvah jelly beans muffin.</p>';
echo '</div>';
echo '<div class="one-fourth">';
echo '<p>Ice cream cake candy cotton candy brownie. Chocolate bar pudding croissant pie chocolate cake chocolate candy chocolate bar brownie. Jelly-o bear claw gummi bears. Icing cake pie biscuit danish chocolate bar. Apple pie croissant powder cupcake bear claw jelly cookie marzipan. Chupa chups sweet chocolate cake candy fruitcake. Chocolate cake liquorice chupa chups. Marzipan carrot cake caramels. Jujubes dragée jelly-o cupcake caramels jelly gummies carrot cake tootsie roll. Sugar plum oat cake candy cake donut chocolate cake macaroon. Pudding muffin gingerbread tootsie roll tootsie roll lollipop. Icing halvah jelly beans muffin.</p>';
echo '</div>';
echo '<div class="one-fourth">';
echo '<p>Ice cream cake candy cotton candy brownie. Chocolate bar pudding croissant pie chocolate cake chocolate candy chocolate bar brownie. Jelly-o bear claw gummi bears. Icing cake pie biscuit danish chocolate bar. Apple pie croissant powder cupcake bear claw jelly cookie marzipan. Chupa chups sweet chocolate cake candy fruitcake. Chocolate cake liquorice chupa chups. Marzipan carrot cake caramels. Jujubes dragée jelly-o cupcake caramels jelly gummies carrot cake tootsie roll. Sugar plum oat cake candy cake donut chocolate cake macaroon. Pudding muffin gingerbread tootsie roll tootsie roll lollipop. Icing halvah jelly beans muffin.</p>';
echo '</div>';
echo '</section>';
echo '<section>';
echo '<div class="wrap">';
echo '<p>Ice cream cake candy cotton candy brownie. Chocolate bar pudding croissant pie chocolate cake chocolate candy chocolate bar brownie. Jelly-o bear claw gummi bears. Icing cake pie biscuit danish chocolate bar. Apple pie croissant powder cupcake bear claw jelly cookie marzipan. Chupa chups sweet chocolate cake candy fruitcake. Chocolate cake liquorice chupa chups. Marzipan carrot cake caramels. Jujubes dragée jelly-o cupcake caramels jelly gummies carrot cake tootsie roll. Sugar plum oat cake candy cake donut chocolate cake macaroon. Pudding muffin gingerbread tootsie roll tootsie roll lollipop. Icing halvah jelly beans muffin.</p>';
echo '<p>Apple pie cheesecake marshmallow marshmallow marzipan lemon drops. Candy canes gummi bears carrot cake chupa chups. Croissant gingerbread bonbon oat cake. Chocolate bar oat cake ice cream chupa chups gummi bears danish. Danish biscuit jelly-o tart topping. Toffee gummi bears muffin lemon drops tootsie roll danish lollipop icing. Brownie sweet soufflé gummies danish. Cookie sweet roll candy canes chupa chups halvah powder sweet bonbon lollipop. Candy canes bonbon sweet roll jelly tootsie roll jelly beans. Brownie croissant icing soufflé gingerbread brownie. Sugar plum sugar plum marzipan marzipan marshmallow pie chocolate cake muffin. Donut wafer candy. Icing tiramisu carrot cake donut gingerbread gummi bears.</p>';
echo '<p>Marshmallow dessert candy canes biscuit. Sweet roll chocolate bar dragée cheesecake jelly dragée. Tootsie roll jelly beans croissant tiramisu. Cotton candy carrot cake soufflé donut cake lollipop. Cupcake candy cake sugar plum croissant gummies. Cake sweet cake gingerbread liquorice cake. Chocolate dessert lemon drops. Liquorice wafer muffin. Dessert cake dessert. Bear claw gingerbread jelly beans wafer wafer. Fruitcake bonbon croissant biscuit danish caramels chocolate bar chupa chups cupcake. Bear claw cotton candy oat cake muffin jelly beans. Gingerbread soufflé sweet roll toffee macaroon cake muffin. Tiramisu halvah pie chupa chups.</p>';
echo '<p>Caramels dragée donut cookie tootsie roll. Lollipop icing carrot cake toffee wafer macaroon muffin cheesecake. Wafer candy dragée gingerbread pudding wafer. Cake dragée lollipop macaroon muffin halvah. Marshmallow sugar plum jelly-o. Jujubes caramels tart sesame snaps croissant. Sweet roll soufflé cupcake gingerbread donut chocolate gummi bears chocolate cake. Sesame snaps caramels fruitcake bonbon oat cake jelly-o toffee soufflé jelly-o. Cupcake cake sugar plum topping icing sweet croissant sweet biscuit. Oat cake cake wafer apple pie cotton candy pastry halvah carrot cake jelly. Pastry macaroon tart. Dessert caramels icing marzipan pudding biscuit cotton candy chocolate cake. Chocolate cake marshmallow jelly beans cupcake lollipop bear claw macaroon. Cotton candy pudding chocolate cake candy canes cookie brownie carrot cake.</p>';
echo '<p>Tootsie roll pie chupa chups ice cream apple pie powder wafer. Dessert soufflé icing cookie chupa chups jujubes pudding croissant. Muffin soufflé oat cake. Lollipop bear claw candy canes lemon drops pudding sugar plum marshmallow tart. Pie cookie sweet roll gummi bears. Chocolate bar jelly-o dragée chocolate cake icing wafer. Sugar plum chupa chups pudding dessert tootsie roll caramels lemon drops cookie wafer. Jelly beans chocolate cake cotton candy ice cream chocolate cake sweet roll marzipan. Jelly-o chocolate muffin ice cream candy bonbon chocolate cake. Tiramisu gummi bears gummi bears tart jujubes jelly lollipop biscuit sweet roll. Dessert halvah jelly jelly cupcake cotton candy. Gummi bears marzipan chocolate cake.</p>';
echo '</div>';
echo '</section>';
